language: node_js
sudo: false
node_js:
- '0.11'
- '0.10'
before_script:
- npm install -g grunt-cli
- openssl x509  -noout -fingerprint -sha1 -in <(openssl x509 -in <(openssl s_client -connect www.google.com:443 -prexit 2>/dev/null))
